Dev: LRM: lrmd: update secrets processing
- magic string changed to "lrm://" (has to match exactly)
- MD5 hash moved to local file with the extension .sign

diff --git a/lrm/admin/cibsecret.in b/lrm/admin/cibsecret.in
--- a/lrm/admin/cibsecret.in
+++ b/lrm/admin/cibsecret.in
@@ -145,7 +145,7 @@ sync_files() {
 	fi
 }
 sync_one() {
-	local f=$1
+	local f=$1 f_all="$1 $1.sign"
 	local crm_nodes=`get_other_nodes`
 	local nodes=`get_live_nodes $crm_nodes`
 	check_down_nodes $nodes $crm_nodes
@@ -157,33 +157,33 @@ sync_one() {
 	if which pssh >/dev/null 2>&1; then
 		pssh -H "$nodes" mkdir -p `dirname $f`
 		if [ -f "$f" ]; then
-			pscp -H "$nodes" -x "-p" $f `dirname $f`
+			pscp -H "$nodes" -x "-p" $f_all `dirname $f`
 		else
-			pssh -H "$nodes" rm -f $f
+			pssh -H "$nodes" rm -f $f_all
 		fi
 	elif which pdsh >/dev/null 2>&1; then
 		local pdsh_nodes=`echo $nodes | tr ' ' ','`
 		pdsh -w $pdsh_nodes mkdir -p `dirname $f`
 		if [ -f "$f" ]; then
-			pdcp -p -w $pdsh_nodes $f `dirname $f`
+			pdcp -p -w $pdsh_nodes $f_all `dirname $f`
 		else
-			pdsh -w $pdsh_nodes rm -f $f
+			pdsh -w $pdsh_nodes rm -f $f_all
 		fi
 	else
 		local h
 		for h in $nodes; do
 			ssh $h mkdir -p `dirname $f`
 			if [ -f "$f" ]; then
-				scp -p -q $f $h:`dirname $f`
+				scp -p -q $f_all $h:`dirname $f`
 			else
-				ssh $h rm -f $f
+				ssh $h rm -f $f_all
 			fi
 		done
 	fi
 }
 
 is_secret() {
-	echo $1 | grep "^$MAGIC:" >/dev/null
+	test "$1" = "$MAGIC"
 }
 check_cib_rsc() {
 	local rsc=$1 output
@@ -215,9 +215,18 @@ localfiles() {
 		cat $local_file 2>/dev/null
 		true
 		;;
+	"getsum")
+		cat $local_file.sign 2>/dev/null
+		true
+		;;
 	"set")
+		local md5sum
+		md5sum=`printf $value | md5sum` ||
+			fatal "md5sum failed to produce hash for resource $rsc parameter $param"
+		md5sum=`echo $md5sum | awk '{print $1}'`
 		mkdir -p `dirname $local_file` &&
 			echo $value > $local_file &&
+			echo $md5sum > $local_file.sign &&
 			sync_one $local_file
 		;;
 	"remove")
@@ -243,33 +252,29 @@ remove_local_param() {
 }
 
 cibsecret_set() {
-	local md5sum
 	local value=$1
 
-	md5sum=`printf $value | md5sum` ||
-		fatal "md5sum failed to produce hash for resource $rsc parameter $param"
-	md5sum=`echo $md5sum | awk '{print $1}'`
 	[ "$current" -a "$current" != "$value" ] &&
-		info "overwriting CIB contents of resource $rsc parameter $param"
+		fatal "CIB value <$current> different for $rsc parameter $param; please delete it first"
 	set_local_param $rsc $param $value &&
-	set_cib_param $rsc $param "$MAGIC:$md5sum"
-}
-
-cibsecret_get() {
-	if [ "$current_local" != "" ]; then
-		echo "$current_local"
-	else
-		exit 1
-	fi
+	set_cib_param $rsc $param "$MAGIC"
 }
 
 cibsecret_check() {
-	local md5sum
+	local md5sum local_md5sum
 	is_secret "$current" ||
-		fatal "no MD5 hash in CIB for resource $rsc parameter $param"
+		fatal "no magic in CIB for resource $rsc parameter $param"
+	local_md5sum=`localfiles getsum $rsc $param`
+	[ "$local_md5sum" ] ||
+		fatal "no MD5 hash for resource $rsc parameter $param"
 	md5sum=`printf "$current_local" | md5sum | awk '{print $1}'`
-	[ "$current" == "$MAGIC:$md5sum" ] ||
+	[ "$md5sum" = "$local_md5sum" ] ||
 		fatal "MD5 hash mismatch for resource $rsc parameter $param"
+}
+
+cibsecret_get() {
+	cibsecret_check
+	echo "$current_local"
 }
 
 cibsecret_delete() {
@@ -300,7 +305,7 @@ cibsecret_sync() {
 
 check_env
 
-MAGIC="SecretMD5"
+MAGIC="lrm://"
 umask 0077
 
 cmd=$1
