Medium: stonith: rename ha_log.sh to stonith_logger and install it in sbin directory
This change gets rid of the setenv(PATH,...) which apparently
introduces a memory leak.

diff --git a/lib/plugins/stonith/external/drac5.in b/lib/plugins/stonith/external/drac5.in
--- a/lib/plugins/stonith/external/drac5.in
+++ b/lib/plugins/stonith/external/drac5.in
@@ -6,16 +6,16 @@
 # License:      GNU General Public License (GPL)
 #
 
-trap 'if [ -n "$outf" ]; then ha_log.sh err "`cat $outf`"; rm -f "$outf"; fi' 0
+trap 'if [ -n "$outf" ]; then stonith_logger err "`cat $outf`"; rm -f "$outf"; fi' 0
 outf=`mktemp` || {
-	ha_log.sh err "mktemp failed"
+	stonith_logger err "mktemp failed"
 	exit 1
 }
 
 sshlogin() {
 	if [ x = "x$ipaddr" -o x = "x$userid" ]
 	then
-		ha_log.sh err "ipaddr or userid missing; check configuration"
+		stonith_logger err "ipaddr or userid missing; check configuration"
 		return 1
 	fi
 	@SSH@ -q -x -n $userid@$ipaddr racadm serveraction "$1" >$outf 2>&1
