High: stonith: external plugins log using ha_log.sh (LF 2294)

diff --git a/lib/plugins/stonith/external/ibmrsa b/lib/plugins/stonith/external/ibmrsa
--- a/lib/plugins/stonith/external/ibmrsa
+++ b/lib/plugins/stonith/external/ibmrsa
@@ -7,37 +7,27 @@
 # This STONITH module depends on IBMmpcli.
 #
 
-#DEBUGF=/var/log/ha-ibmrsa.log
-#touch $DEBUGF
-#chmod 600 $DEBUGF
-
-#exec 2>>$DEBUGF
-
-#debug() {
-#	cat >&2
-#}
-
-#echo "started with: $@" | debug
-
-trap 'if [ -n "$outf" ]; then cat "$outf" >&2; rm -f "$outf"; fi' 0
-outf=`mktemp` || exit 1
+trap 'if [ -n "$outf" ]; then ha_log.sh err "`cat $outf`"; rm -f "$outf"; fi' 0
+outf=`mktemp` || {
+	ha_log.sh err 'mktemp failed'
+	exit 1
+}
 
 chkmpcli() {
 	test -x /opt/IBMmpcli/bin/MPCLI.sh
 }
 mpcli() {
 	chkmpcli || {
-		echo "IBM mpcli not installed"
+		ha_log.sh err "IBM mpcli not installed"
 		return 1
 	}
 	if [ x = "x$ipaddr" -o x = "x$userid" -o x = "x$passwd" ]
 	then
-		echo "ipaddr, userid, or passwd missing; check configuration"
+		ha_log.sh err "ipaddr, userid, or passwd missing; check configuration"
 		return 1
 	fi
 	type=${type:-"ibm"}
 
-	test -f /etc/ha.d/ibmrsa.debug && set -x
 	goodstg="SUCCESS"
 	failstg="FAILURE"
 	(
@@ -47,7 +37,12 @@ mpcli() {
 	) | /opt/IBMmpcli/bin/MPCLI.sh | grep -w $goodstg >/dev/null 2>&1
 	rc=$?
 	grep -w $failstg $outf
-	test $rc -eq 0 -a $? -eq 1
+	if [ $rc -eq 0 -a $? -eq 1 ]; then
+		return 0
+	else
+		ha_log.sh err "MPCLI.sh failed: `cat $outf`"
+		return 1
+	fi
 }
 ibmrsa_reboot() {
 	echo restart -now | mpcli
